version: 0.2
phases:
    install:
        runtime-versions:
            dotnet: 8.0
    build:
        commands:
          - dotnet restore OpenWeatherForecast.sln
          - dotnet build OpenWeatherForecast.sln
          - dotnet test OpenWeatherForecast.sln
    post_build:
        commands:
          - dotnet publish -c Release -r linux-x64 -o ./ src/OpenWeatherForecast.Api/OpenWeatherForecast.Api.csproj
artifacts:
  files:
    - ./**/*
