name: Dev And Test Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  pr-checks:
    uses: Punam-Dev/dotnet-helm-tf-deployment/.github/workflows/dotnet-deploy.yaml@main
    secrets: inherit
    with:
      dotnet-version: '8.0.x'
      app-name: openweatherforecast-api
      sln-path: 'OpenWeatherForecast.sln'
      tf-path: 'deploy/infra'
      role-name: 'openwatherforecast-terraform'
