name: PR Checks

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  pr-checks:
    uses: Punam-Dev/dotnet-helm-tf-deployment/.github/workflows/dotnet-pr-checks.yaml@main
    with:
      dotnet-version: '8.0.x'
      sln-path: 'OpenWeatherForecast.sln'